[server]
address=":80"

[cors]
allow-origins=["*"]
allow-methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allow-headers=["*"]
allow-credentials=false
max-age=86400

[database]
driver-name="sqlite3"
data-source-name="inventory.db"
max-idle-conns=2
max-open-conns=10
max-lifetime=60