import Mock from 'mockjs';
const treeData = [{
        "id":1,
        "code":"AC",
        "category":"AC-AP-FAU-000",
        "description":"空调系统",
        "seq":10,
        "level":"1",
        "parent_id":0,
        "type":"device",
        "remark":"fdsa",
        "is_std":1,
        "std_id":"",
        "has_children":"1",
        "change_by":"侯刚",
        "change_date":"2015-05-24",
        "create_by":"1979-06-09",
        "is_active":1
    },{
        "id":2,
        "code":"AP",
        "category":"",
        "description":"空气处理系统",
        "seq":10,
        "level":"2",
        "remark":"fdsa",
        "parent_id":1,
        "type":"device",
        "is_std":"",
        "std_id":"",
        "has_children":"1",
        "change_by":"毛洋",
        "change_date":"2007-02-28",
        "create_by":"2016-02-17",
        "is_active":1
    },{
        "id":3,
        "code":"FAU",
        "category":"",
        "description":"新风处理机组",
        "seq":10,
        "level":"3",
        "remark":"fdsa",
        "parent_id":2,
        "type":"device",
        "is_std":"",
        "std_id":"",
        "has_children":"0",
        "change_by":"石强",
        "change_date":"2000-06-07",
        "create_by":"2005-03-16",
        "is_active":0
    },{
        "id":4,
        "code":"FCU",
        "category":"",
        "description":"风机盘管",
        "seq":20,
        "level":"3",
        "remark":"fdsa",
        "parent_id":2,
        "type":"device",
        "is_std":"",
        "std_id":"",
        "has_children":"0",
        "change_by":"钱娟",
        "change_date":"1985-12-08",
        "create_by":"2013-03-24",
        "is_active":0
    },{"id":5,
        "code":"CH",
        "category":"",
        "description":"供冷采暖",
        "seq":20,
        "level":"2",
        "remark":"fdsa",
        "parent_id":1,
        "type":"device",
        "is_std":"",
        "std_id":"",
        "has_children":"1",
        "change_by":"蔡丽",
        "change_date":"2013-07-22",
        "create_by":"1985-12-08",
        "is_active":0
    },{"id":6,
        "code":"XZL",
        "category":"",
        "description":"测试1",
        "seq":30,
        "level":"3",
        "remark":"fdsa",
        "parent_id":5,
        "type":"device",
        "is_std":"",
        "std_id":"",
        "has_children":"0",
        "change_by":"毛强",
        "change_date":"2016-03-12",
        "create_by":"1996-06-18",
        "is_active":1
    },{
        "id":7,
        "code":"ES",
        "category":"",
        "description":"电梯升降系统",
        "seq":20,
        "level":"1",
        "remark":"fdsa",
        "parent_id":0,
        "type":"device",
        "is_std":"",
        "std_id":"",
        "has_children":"0",
        "change_by":"陈芳",
        "change_date":"1979-11-17",
        "create_by":"1980-02-22",
        "is_active":1
}];
//------------------------------------------------------business----------------------------------------------------------------
var BusinessData = Mock.mock({
    'Business|20': [{
    'id|+1': 1,
    'description|1':Mock.Random.csentence(2),
    code: 'XZL',
    'seq|+10':10,
    remark:Mock.Random.csentence(),
    is_std:'',
    'change_by|1': Mock.Random.cname(),
    change_date: Mock.Random.date(),
    create_by: Mock.Random.cname(),
    'is_active|1': true,
    }]
});
BusinessData.total = 20;
//------------------------------------------------------numberdict----------------------------------------------------------------

var NumberdictData = Mock.mock({
        'Numberdict|20': [{
        'id|+1': 10,
        code: 'XCZ',
        'desc_zh|1':Mock.Random.csentence(2),
        'seq|+10':10,
        type:'a',
        remark:Mock.Random.csentence(),
        'change_by|1': Mock.Random.cname(),
        change_date: Mock.Random.date(),
        create_by: Mock.Random.cname(),
        'is_active|1': true,
    }]
});
NumberdictData.total = 20;
NumberdictData.type = [{
    'id': 0,
    "code": 'x',
    'desc_zh':'数字字典类型',
    'seq':10,
    'type':'type',
    remark:Mock.Random.csentence(),
    change_by: Mock.Random.cname(),
    change_date: Mock.Random.date(),
    create_by: Mock.Random.cname(),
    'is_active|1': true,
},{
    'id': 1,
    "code": 'a',
    'desc_zh':'a类',
    'seq':10,
    'type':'x',
    remark:Mock.Random.csentence(),
    change_by: Mock.Random.cname(),
    change_date: Mock.Random.date(),
    create_by: Mock.Random.cname(),
    create_date: Mock.Random.date(),
    'is_active|1': true,
},{
    'id': 2,
    "code": 'b',
    'desc_zh':'b类',
    'seq':20,
    'type':'x',
    remark:Mock.Random.csentence(),
    change_by: Mock.Random.cname(),
    change_date: Mock.Random.date(),
    create_by: Mock.Random.cname(),
    create_date: Mock.Random.date(),
    'is_active|1': true,
},{
    'id': 3,
    "code": 'c',
    'desc_zh':'c类',
    'seq':30,
    'type':'x',
    remark:Mock.Random.csentence(),
    change_by: Mock.Random.cname(),
    change_date: Mock.Random.date(),
    create_by: Mock.Random.cname(),
    create_date: Mock.Random.date(),
    'is_active|1': true,
}];
export { BusinessData,treeData, NumberdictData};
